--- Makefile	2013-04-20 12:40:56.945079969 +0800
+++ Makefile	2013-04-20 12:45:19.173951796 +0800
@@ -208,20 +218,23 @@
 
 .PHONY: qemu qemu-nox debug debug-nox
 qemu: $(UCOREIMG)
-	$(V)$(QEMU) -parallel stdio -hda $< -serial null
+	$(V)$(QEMU) -hda $< -parallel stdio
 
 qemu-nox: $(UCOREIMG)
-	$(V)$(QEMU) -serial mon:stdio -hda $< -nographic
+	$(V)$(QEMU) -serial mon:stdio -parallel stdio -serial stdio -hda $< -nographic
 TERMINAL        :=gnome-terminal
 debug: $(UCOREIMG)
 	$(V)$(QEMU) -S -s -parallel stdio -hda $< -serial null &
 	$(V)sleep 2
 	$(V)$(TERMINAL) -e "gdb -q -x tools/gdbinit"
-	
+
 debug-nox: $(UCOREIMG)
 	$(V)$(QEMU) -S -s -serial mon:stdio -hda $< -nographic &
-	$(V)sleep 2
-	$(V)$(TERMINAL) -e "gdb -q -x tools/gdbinit"
+#	$(V)sleep 5
+#	$(V)$(TERMINAL) -e "gdb -q -x tools/gdbinit"
+
+hello: $(UCOREIMG)
+	@echo "hello"
 
 .PHONY: grade touch
 
